services:
  mariadb:
    image: 'mariadb:latest'
    container_name: mariadb
    environment:
      - MARIADB_DATABASE=fluxo-caixa
      - MARIADB_USER=myuser
      - MARIADB_PASSWORD=secret
      - MARIADB_ROOT_PASSWORD=verysecret
    ports:
      - '3306:3306'
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend

  app:
    image: 'openjdk:17-slim'
    container_name: spring-app
    depends_on:
      - mariadb
    ports:
      - '8080:8080'
    volumes:
      - ./:/app
    working_dir: /app
    command: ["./mvnw", "spring-boot:run"]
    networks:
      - backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/fluxo-caixa
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: secret
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mariadb_data:

networks:
  backend:
